version: '3.4'
services:
  envoygateway:
      build: Envoy/
      ports:
        - "9901:9901"
        - "10000:10000"
        - "10001:10001"
      volumes:
        - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
        - ./Envoy/https.crt:/etc/ssl/certs/https.crt
        - ./Envoy/key.pem:/etc/ssl/certs/key.pem
  coffeeapi:
    build: CoffeeApi/
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - C:\Users\Ahmet\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets
      - C:\Users\Ahmet\.asp.net\https:/root/.aspnet/https

  teaapi:
    build: TeaApi/
    ports:
      - "8082:80"
      - "8083:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8083"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - C:\Users\Ahmet\AppData\Roaming\Microsoft\UserSecrets:/root/.microsoft/usersecrets
      - C:\Users\Ahmet\.asp.net\https:/root/.aspnet/https